SELECT 
p.[ProductKey]
,p.[ProductAlternateKey]  as ProductItemCode
--      ,[ProductSubcategoryKey]
--      ,[WeightUnitMeasureCode]
--      ,[SizeUnitMeasureCode]
,p.[EnglishProductName] as [Product Name]
,ps.[EnglishProductSubcategoryName] as [Sub Category]
,pc.[EnglishProductcategoryName] as [Product Category]
--,[SpanishProductName]
--      ,[FrenchProductName]
--      ,[StandardCost]
--      ,[FinishedGoodsFlag]
,p.[Color] as [Product Color]
--        ,[SafetyStockLevel]
--      ,[ReorderPoint]
--      ,[ListPrice]
,p.[Size] as [Product Size]
--      ,[SizeRange]
--      ,[Weight]
--      ,[DaysToManufacture]
,p.[ProductLine] as [Product Line]
--      ,[DealerPrice]
--      ,[Class]
--      ,[Style]
,p.[ModelName] as [Product Model Name]
--      ,[LargePhoto]
,p.[EnglishDescription] as [Product Descreption]
--      ,[FrenchDescription]
--      ,[ChineseDescription]
--      ,[ArabicDescription]
--      ,[HebrewDescription]
--      ,[ThaiDescription]
--     ,[GermanDescription]
--      ,[JapaneseDescription]
--      ,[TurkishDescription]
--      ,[StartDate]
--      ,[EndDate]
,isnull (p.Status,'Outedated') as [Product Statues]
FROM 
	[dbo].[DimProduct] as p
	left join [dbo].[DimProductSubcategory] as ps on ps.productsubcategorykey = p.productsubcategorykey
	left join [dbo].[DimProductCategory] as pc on ps.productcategorykey = pc.productcategorykey
order by
	p.ProductKey asc